version: "3.3"  # optional since v1.27.0

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  referee:
    build: .
    environment:
      RABBIT_MQ_HOSTNAME: rabbitmq
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_PORT: 5672
      ADMINISTRATION_EXECHANGE_NAME: referee
      REFEREE_GAME_TOPIC_NAME: games
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    entrypoint: ./entrypoint.sh
  